# Generated by Django 6.0.1 on 2026-03-24 17:21

import Aplicaciones.sbr_app_dos.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('numero_recibo', models.CharField(blank=True, help_text='Número de recibo (Opcional)', max_length=50, null=True)),
                ('foto_recibo', models.ImageField(blank=True, help_text='Foto del recibo (Opcional)', null=True, upload_to='gestor/recibos/', validators=[Aplicaciones.sbr_app_dos.validators.validar_archivo_seguro])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
