# Generated by Django 6.0.1 on 2026-03-24 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='transaccion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sbr_gestor.categoriatransaccion'),
        ),
    ]
