# Generated by Django 6.0.1 on 2026-01-16 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mora_leve_dias', models.IntegerField(default=5, help_text='Días para aplicar primera mora')),
                ('mora_leve_valor', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('mora_media_dias', models.IntegerField(default=10)),
                ('mora_media_valor', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('mora_grave_dias', models.IntegerField(default=20)),
                ('mora_grave_valor', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('ruc_empresa', models.CharField(max_length=13)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzana', models.CharField(max_length=10)),
                ('numero_lote', models.CharField(max_length=10)),
                ('dimensiones', models.CharField(help_text='Ej: 10x20m', max_length=50)),
                ('precio_contado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido')], default='DISPONIBLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_clientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contrato', models.DateField()),
                ('archivo_contrato_pdf', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('precio_venta_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_a_financiar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_cuotas', models.IntegerField()),
                ('esta_en_mora', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbr_app_dos.cliente')),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sbr_app_dos.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_mora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido/Mora')], default='PENDIENTE', max_length=20)),
                ('fecha_ultimo_pago', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='sbr_app_dos.contrato')),
            ],
            options={
                'ordering': ['numero_cuota'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia/Depósito')], max_length=20)),
                ('comprobante_imagen', models.ImageField(blank=True, null=True, upload_to='pagos/comprobantes/')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbr_app_dos.contrato')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
