# Generated by Django 6.0.1 on 2026-01-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado/Finalizado'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=20),
        ),
    ]
