# Generated by Django 6.0.1 on 2026-01-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0002_contrato_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado/Finalizado'), ('ANULADO', 'Anulado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20),
        ),
    ]
