# Generated by Django 6.0.1 on 2026-01-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0003_alter_contrato_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha_cancelacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado/Finalizado'), ('ANULADO', 'Anulado'), ('CANCELADO', 'Cancelado'), ('DEVOLUCION', 'Devolución')], default='ACTIVO', max_length=20),
        ),
    ]
