# Generated by Django 6.0.1 on 2026-01-20 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0004_contrato_fecha_cancelacion_alter_contrato_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbr_app_dos.lote'),
        ),
    ]
