# Generated by Django 6.0.1 on 2026-01-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0006_lote_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto del lote (opcional)', null=True, upload_to='lotes/'),
        ),
    ]
