# Generated by Django 6.0.1 on 2026-01-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0007_add_imagen_to_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante_imagen',
            field=models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/'),
        ),
    ]
