# Generated by Django 6.0.1 on 2026-01-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0008_alter_pago_comprobante_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='canton',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='lindero_este',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='lindero_norte',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='lindero_oeste',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='lindero_sur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='nombre_lote',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='parroquia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
