# Generated by Django 6.0.1 on 2026-01-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0010_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='lindero_este',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='lindero_norte',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='lindero_oeste',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='lindero_sur',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='nombre_lote',
        ),
    ]
