# Generated by Django 6.0.1 on 2026-01-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0011_remove_lote_calle_remove_lote_lindero_este_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
    ]
