# Generated by Django 6.0.1 on 2026-01-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0012_alter_cliente_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='mora_exenta',
            field=models.BooleanField(default=False, help_text='Si está marcado, esta cuota NO tendrá mora aunque esté vencida'),
        ),
    ]
