# Generated by Django 6.0.1 on 2026-01-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0013_cuota_mora_exenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='mora_porcentaje',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Porcentaje de mora sobre el capital de la cuota (Ej: 3.00 = 3%)', max_digits=5),
        ),
    ]
