# Generated by Django 6.0.1 on 2026-01-26 17:07

import Aplicaciones.sbr_app_dos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0015_logactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banco',
            field=models.CharField(blank=True, help_text='Nombre del Banco', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_cuenta',
            field=models.CharField(blank=True, help_text='Número de cuenta bancaria', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='config/logos/', validators=[Aplicaciones.sbr_app_dos.validators.validar_archivo_seguro]),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='archivo_contrato_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', validators=[Aplicaciones.sbr_app_dos.validators.validar_archivo_seguro]),
        ),
        migrations.AlterField(
            model_name='lote',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto del lote (opcional)', null=True, upload_to='lotes/', validators=[Aplicaciones.sbr_app_dos.validators.validar_archivo_seguro]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante_imagen',
            field=models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/', validators=[Aplicaciones.sbr_app_dos.validators.validar_archivo_seguro]),
        ),
    ]
