# Generated by Django 6.0.1 on 2026-02-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0016_perfil_banco_perfil_numero_cuenta_perfil_tipo_cuenta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='lote',
        ),
        migrations.AddField(
            model_name='contrato',
            name='lotes',
            field=models.ManyToManyField(related_name='contratos', to='sbr_app_dos.lote'),
        ),
    ]
