# Generated by Django 6.0.1 on 2026-02-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0017_multiple_lotes_per_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='lotes',
        ),
        migrations.AddField(
            model_name='contrato',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sbr_app_dos.lote'),
        ),
    ]
