# Generated by Django 6.0.1 on 2026-02-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0018_remove_contrato_lotes_contrato_lote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='fecha_cancelacion',
            new_name='fecha_fin_contrato',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='precio_venta_final',
        ),
        migrations.AddField(
            model_name='contrato',
            name='lotes',
            field=models.ManyToManyField(blank=True, related_name='contratos', to='sbr_app_dos.lote'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='archivo_contrato_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos_pdfs/'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='saldo_a_financiar',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
