# Generated by Django 6.0.1 on 2026-02-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0019_rename_fecha_cancelacion_contrato_fecha_fin_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='precio_venta_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
