# Generated by Django 6.0.1 on 2026-02-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0020_contrato_precio_venta_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='numero_lote',
            field=models.CharField(max_length=30),
        ),
    ]
