# Generated by Django 6.0.1 on 2026-02-09 21:58

import Aplicaciones.sbr_app_dos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0021_alter_lote_numero_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='foto_lista',
            field=models.ImageField(blank=True, help_text='Foto para mostrar en el listado (opcional)', null=True, upload_to='lotes/portadas/', validators=[Aplicaciones.sbr_app_dos.validators.validar_archivo_seguro]),
        ),
    ]
