# Generated by Django 6.0.1 on 2026-02-09 22:13

import Aplicaciones.sbr_app_dos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0022_lote_foto_lista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='imagen',
        ),
        migrations.AddField(
            model_name='lote',
            name='plano',
            field=models.ImageField(blank=True, help_text='Imagen del plano/mapa del lote', null=True, upload_to='lotes/planos/', validators=[Aplicaciones.sbr_app_dos.validators.validar_archivo_seguro]),
        ),
    ]
