# Generated by Django 6.0.1 on 2026-02-17 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0023_remove_lote_imagen_lote_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, help_text='Monto de este pago destinado a esta cuota', max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_asociados', to='sbr_app_dos.cuota')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sbr_app_dos.pago')),
            ],
        ),
    ]
