# Generated by Django 6.0.1 on 2026-02-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0024_detallepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='numero_transaccion',
            field=models.IntegerField(blank=True, help_text='Número secuencial del pago dentro del contrato', null=True),
        ),
    ]
