# Generated by Django 6.0.1 on 2026-02-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0025_pago_numero_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='mora_grave_dias',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='mora_grave_valor',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='mora_leve_dias',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='mora_leve_valor',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='mora_media_dias',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='mora_media_valor',
        ),
    ]
