# Generated by Django 6.0.1 on 2026-03-02 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbr_app_dos', '0026_remove_configuracionsistema_mora_grave_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cuota_origen',
            field=models.ForeignKey(blank=True, help_text='Si seleccionó una cuota intencionalmente al pagar, este campo la guarda para recordarlo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sbr_app_dos.cuota'),
        ),
        migrations.AddField(
            model_name='pago',
            name='es_entrada',
            field=models.BooleanField(default=False, help_text='Indica si este pago corresponde a la cuota de entrada no amortizable'),
        ),
    ]
