"""
Django settings for sbr project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Configuración de GTK para WeasyPrint en Windows
GTK_FOLDER = r'C:\Program Files\GTK3-Runtime Win64\bin'
if os.name == 'nt':
    if os.path.exists(GTK_FOLDER):
        os.environ['PATH'] = GTK_FOLDER + ';' + os.environ['PATH']

# Recaptcha Settings
RECAPTCHA_PUBLIC_KEY = (os.getenv('RECAPTCHA_PUBLIC_KEY') or '').strip()
RECAPTCHA_PRIVATE_KEY = (os.getenv('RECAPTCHA_PRIVATE_KEY') or '').strip()
SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error'] # Silenciar alerta de claves de prueba

# Configuración de Axes (Seguridad contra Fuerza Bruta)
AXES_FAILURE_LIMIT = 5            # Bloquear tras 5 intentos fallidos
AXES_COOLOFF_TIME = 1             # Bloquear por 1 hora
AXES_RESET_ON_SUCCESS = True      # Resetear contador al entrar bien
# AXES_LOCKOUT_TEMPLATE = 'lockout.html'  # Opcional

# Configuración correcta de Backends de Autenticación
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend', # Backend de Axes (Primero)
    'django.contrib.auth.backends.ModelBackend', # Backend por defecto de Django
]

# 1. Primero definimos la ruta base (BASE_DIR)
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Ahora construimos la ruta exacta al archivo .env
env_path = BASE_DIR / '.env'

# 3. Y finalmente cargamos ese archivo específico
load_dotenv(env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
# Secure by default: If DJANGO_ENV is not set, DEBUG will be False
DEBUG = os.getenv('DJANGO_ENV') == 'development'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'axes', # Protección contra ataques de fuerza bruta
    'django_recaptcha', # Google Recaptcha
    'Aplicaciones.sbr_app_dos',
]

MIDDLEWARE = [
    'sbr_dos.middleware.ForceCSPMiddleware', # CSP Personalizado (Primero)
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware', # Middleware de Axes
]

ROOT_URLCONF = 'sbr_dos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sbr_dos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv('DJANGO_ENV') == 'production':
    # Ruta de producción en PythonAnywhere
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': '/home/bienesraices2026/sbr/sbr_db.sqlite3',
        }
    }
else:
    # Ruta local para desarrollo
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'sbr'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (Archivos subidos por usuario como el Logo)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración de Login
LOGIN_REDIRECT_URL = '/'  # A donde va al iniciar sesión (área de gestión)
LOGOUT_REDIRECT_URL = 'login'     # A donde va al salir

# Gestión de Sesiones (Seguridad 4.1)
SESSION_COOKIE_AGE = 900        # 15 minutos (en segundos)
SESSION_SAVE_EVERY_REQUEST = True # Reiniciar contador si hay actividad (Inactividad real)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Cerrar sesión al cerrar navegador

# Configuraciones de seguridad para producción
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
    if csrf_origins:
        CSRF_TRUSTED_ORIGINS = csrf_origins.split(',')


JAZZMIN_SETTINGS = {
    # Título que sale en la pestaña del navegador
    "site_title": "Bienes Raíces Admin",

    # Título en la pantalla de login
    "site_header": "Administración SBR",

    # Enlaces del menú superior (Aquí va tu botón)
    "topmenu_links": [
        # Botón para ir al inicio (la parte pública)
        {
            "name": "Ir al Dashboard",  # Texto del botón
            "url": "/",                 # La ruta (puede ser "/" o el nombre de la url como 'dashboard')
            "new_window": True,         # ¿Abrir en nueva pestaña? (True/False)
            "icon": "fas fa-home",      # Icono de FontAwesome
            "permissions": ["auth.view_user"], # Solo mostrar a quien tenga permiso (opcional)
        },
    ],
    
    # Opcional: Para que el logo de arriba a la izquierda también lleve al inicio
    # "site_logo": "img/logo.png", 
}


